-- Lets staff pause/remove events without a developer, and lets volunteers
-- report back what happened after a shift. Also makes event_id/school_id
-- auto-generate so the app can create new rows without knowing the next id.

ALTER TABLE EVENT
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active',
    ADD COLUMN IF NOT EXISTS report_notes TEXT,
    ADD COLUMN IF NOT EXISTS prospects_count INT;

DO $$ BEGIN
    ALTER TABLE EVENT ALTER COLUMN event_id ADD GENERATED BY DEFAULT AS IDENTITY;
EXCEPTION WHEN others THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE SCHOOL ALTER COLUMN school_id ADD GENERATED BY DEFAULT AS IDENTITY;
EXCEPTION WHEN others THEN NULL;
END $$;

-- Keep the identity sequences ahead of any manually-inserted ids from seed.sql.
SELECT setval(pg_get_serial_sequence('EVENT', 'event_id'), COALESCE((SELECT MAX(event_id) FROM EVENT), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('SCHOOL', 'school_id'), COALESCE((SELECT MAX(school_id) FROM SCHOOL), 0) + 1, false);

CREATE INDEX IF NOT EXISTS idx_event_status ON EVENT(status);
